language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

before_script:
  - if [ $TRAVIS_PHP_VERSION = "7.0" ]; then COVERAGE="--coverage-clover=clover.xml"; fi

script:
  - vendor/bin/phpunit $COVERAGE
  - tests/lint.sh

after_success:
  - if [ "$COVERAGE" != "" ]; then vendor/bin/coveralls; fi

git:
  depth: 5
